### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [sobotka/blender-addons-contrib#1]
Hi,

Thank you for the amazing repo! Is it possible to show how to install one specific add on? I have tried to just install using blender add-ons page the random rocks generator (by selecting the `__init__.py` file) but I am not able to see the add on later on inside blender.

Thank you!

Cheers,

Francesco

**Comment by sobotka** [comment]
This is a mirror. It’s installed by default.
